### PR TITLE
new screen Ops on /

### PR DESCRIPTION
**Pull request by tetris-hermetris**
I find it very helpful to see all the list right inside SG. But maybe it can be a better content formatting (or any magic way to parse it directly from [help.adoc](https://github.com/ul/sound-garden-0x2/blob/master/audio_program/src/help.adoc)). 
I don't know, maybe we need discuss it.

### CODE REVIEW

**Comment by ul** [comment]
This is a great idea! But I'm a bit worried that help.adoc and ops.txt would go out-of-sync. I think that the option of parsing is better.

**Comment by ul** [comment]
But do we need to transform it at all? I think asciidoc format is human-readable enough. We can keep it simple and just render `help.adoc` file which is already conveniently exposed as `audio_program::HELP` constant. What do you think?

**Comment by tetris-hermetris** [comment]
You're right, up-to-date problem is very important. `help.adoc` is ok to read it, but it's very long and not very suitable for quick look. Maybe we need some parsing?
I've got some sleep and have some new thoughts).
Maybe it would be more handy to get access to a flat list of just ops separated by comma.
Something like that:

=== Stack manipulations
pop, dup, swap, rot, dig:<N>,

=== Oscillators
saw, w, tri, t, pulse, p, sine, s, cosine, c

=== Basics
silence, whiteNoise, noise, n, linlin, project, Note that ranges are just signals and are allowed to vary in tim, ange, r, unit, circle, sh, ssh, db2amp, db2a, amp2db, a2db, freq2midi, f2m, midi2freq, m2f, quantize, q, channel:<N>, ch:<N>

And the details are already shown from above in edit mode. 

On other hand it needs additional code to parse it that way, and I can't figure out if that's even reasonable.

**Comment by ul** [comment]
That's not hard to do, we already do parsing to show help in edit mode. We can have a bit more info there and then generate those lists. Let me give it a crack.

**Pull request merged**
